{ "!",	prim_bang,	0, 2, 0, { INST_T_v, INST_T_ANY, }, { INST_T_NONE } },
{ "%",	prim_mod,	0, 2, 1, { INST_T_n, INST_T_n, }, { INST_T_n, } },
{ "*",	prim_mul,	0, 2, 1, { INST_T_n, INST_T_n, }, { INST_T_n, } },
{ "+",	prim_add,	0, 2, 1, { INST_T_n, INST_T_n, }, { INST_T_n, } },
{ "-",	prim_sub,	0, 2, 1, { INST_T_n, INST_T_n, }, { INST_T_n, } },
{ "/",	prim_div,	0, 2, 1, { INST_T_n, INST_T_n, }, { INST_T_n, } },
{ ":",	NULL,	0, 0, 0, { INST_T_NONE }, { INST_T_NONE } },
{ ";",	NULL,	0, 0, 0, { INST_T_NONE }, { INST_T_NONE } },
{ "<",	prim_lessthan,	0, 2, 1, { INST_T_n, INST_T_n, }, { INST_T_n, } },
{ "<=",	prim_lesseq,	0, 2, 1, { INST_T_n, INST_T_n, }, { INST_T_n, } },
{ "=",	prim_equal,	0, 2, 1, { INST_T_n, INST_T_n, }, { INST_T_n, } },
{ ">",	prim_gtrthan,	0, 2, 1, { INST_T_n, INST_T_n, }, { INST_T_n, } },
{ ">=",	prim_gtreq,	0, 2, 1, { INST_T_n, INST_T_n, }, { INST_T_n, } },
{ "@",	prim_at,	0, 1, 1, { INST_T_v, }, { INST_T_ANY, } },
{ "__INTERNAL_XA",	prim_getpropv_i,	0, 2, 1, { INST_T_S, INST_T_O, }, { INST_T_n, } },
{ "__INTERNAL_XB",	prim_getprops_i,	0, 2, 1, { INST_T_S, INST_T_O, }, { INST_T_s, } },
{ "__INTERNAL_XC",	prim_getpropd_i,	0, 2, 1, { INST_T_S, INST_T_O, }, { INST_T_o, } },
{ "__INTERNAL_XD",	prim_rmvprop_i,	0, 2, 0, { INST_T_S, INST_T_O, }, { INST_T_NONE } },
{ "__INTERNAL_XE",	prim_addprop_i,	0, 4, 0, { INST_T_n, INST_T_s, INST_T_S, INST_T_O, }, { INST_T_NONE } },
{ "__INTERNAL_XF",	prim_setprop_i,	0, 3, 0, { INST_T_ANY, INST_T_S, INST_T_O, }, { INST_T_NONE } },
{ "__INTERNAL_XG",	prim_flagp_i,	0, 2, 1, { INST_T_S, INST_T_O, }, { INST_T_n, } },
{ "addpennies",	prim_addpennies,	0, 2, 0, { INST_T_n, INST_T_O, }, { INST_T_NONE } },
{ "addprop",	prim_addprop,	0, 4, 0, { INST_T_n, INST_T_s, INST_T_S, INST_T_O, }, { INST_T_NONE } },
{ "and",	prim_and,	0, 2, 1, { INST_T_ANY, INST_T_ANY, }, { INST_T_n, } },
{ "atoi",	prim_atoi,	0, 1, 1, { INST_T_s, }, { INST_T_n, } },
{ "awake?",	prim_awakep,	0, 1, 1, { INST_T_O, }, { INST_T_n, } },
{ "call",	prim_call,	0, 1, 0, { INST_T_O, }, { INST_T_NONE } },
{ "check_moveto",	prim_check_moveto,	0, 2, 1, { INST_T_Oh, INST_T_O, }, { INST_T_s, } },
{ "conboot",	prim_conboot,	1, 1, 0, { INST_T_c, }, { INST_T_NONE } },
{ "concount",	prim_concount,	0, 0, 1, { INST_T_NONE }, { INST_T_n, } },
{ "condbref",	prim_condbref,	0, 1, 1, { INST_T_c, }, { INST_T_O, } },
{ "conhost",	prim_conhost,	1, 1, 1, { INST_T_c, }, { INST_T_s, } },
{ "conidle",	prim_conidle,	0, 1, 1, { INST_T_c, }, { INST_T_n, } },
{ "connections",	prim_connections,	0, 0, 1, { INST_T_NONE }, { INST_T_LIST, INST_T_c, } },
{ "contents",	prim_contents,	0, 1, 1, { INST_T_O, }, { INST_T_o, } },
{ "contime",	prim_contime,	0, 1, 1, { INST_T_c, }, { INST_T_n, } },
{ "copyobj",	prim_copyobj,	0, 1, 1, { INST_T_O, }, { INST_T_o, } },
{ "dbcmp",	prim_dbcmp,	0, 2, 1, { INST_T_o, INST_T_o, }, { INST_T_n, } },
{ "dbref",	prim_dbref,	0, 1, 1, { INST_T_n, }, { INST_T_o, } },
{ "dbtop",	prim_dbtop,	0, 0, 1, { INST_T_NONE }, { INST_T_o, } },
{ "depth",	prim_depth,	0, 0, 1, { INST_T_NONE }, { INST_T_n, } },
{ "desc",	prim_desc,	0, 1, 1, { INST_T_O, }, { INST_T_s, } },
{ "drop",	prim_drop,	0, 1, 1, { INST_T_O, }, { INST_T_s, } },
{ "dup",	prim_dup,	0, 1, 2, { INST_T_ANY, }, { INST_T_ANY, INST_T_ANY, } },
{ "else",	NULL,	0, 0, 0, { INST_T_NONE }, { INST_T_NONE } },
{ "execute",	prim_execute,	0, 1, 0, { INST_T_a, }, { INST_T_NONE } },
{ "exit",	NULL,	0, 0, 0, { INST_T_NONE }, { INST_T_NONE } },
{ "exit?",	prim_exitp,	0, 1, 1, { INST_T_O, }, { INST_T_n, } },
{ "exits",	prim_exits,	0, 1, 1, { INST_T_P, }, { INST_T_o, } },
{ "explode",	prim_explode,	0, 2, 1, { INST_T_S, INST_T_s, }, { INST_T_LIST, INST_T_s, } },
{ "fail",	prim_fail,	0, 1, 1, { INST_T_O, }, { INST_T_s, } },
{ "flag?",	prim_flagp,	0, 2, 1, { INST_T_S, INST_T_O, }, { INST_T_n, } },
{ "getlink",	prim_getlink,	0, 1, 1, { INST_T_O, }, { INST_T_o, } },
{ "getpropdbref",	prim_getpropd,	0, 2, 1, { INST_T_S, INST_T_O, }, { INST_T_o, } },
{ "getpropstr",	prim_getprops,	0, 2, 1, { INST_T_S, INST_T_O, }, { INST_T_s, } },
{ "getpropval",	prim_getpropv,	0, 2, 1, { INST_T_S, INST_T_O, }, { INST_T_n, } },
{ "if",	NULL,	0, 1, 0, { INST_T_ANY, }, { INST_T_NONE } },
{ "instr",	prim_instr,	0, 2, 1, { INST_T_S, INST_T_s, }, { INST_T_n, } },
{ "int",	prim_int,	0, 1, 1, { INST_T_ANY, }, { INST_T_n, } },
{ "intostr",	prim_intostr,	0, 1, 1, { INST_T_ANY, }, { INST_T_S, } },
{ "location",	prim_loc,	0, 1, 1, { INST_T_O, }, { INST_T_o, } },
{ "match",	prim_match,	0, 1, 1, { INST_T_S, }, { INST_T_o, } },
{ "moveto",	prim_moveto,	0, 2, 0, { INST_T_Oh, INST_T_O, }, { INST_T_NONE } },
{ "name",	prim_name,	0, 1, 1, { INST_T_O, }, { INST_T_S, } },
{ "next",	prim_next,	0, 1, 1, { INST_T_O, }, { INST_T_o, } },
{ "not",	prim_not,	0, 1, 1, { INST_T_ANY, }, { INST_T_n, } },
{ "notify",	prim_notify,	0, 2, 0, { INST_T_s, INST_T_O, }, { INST_T_NONE } },
{ "notify_except",	prim_notify_except,	0, 3, 0, { INST_T_s, INST_T_o, INST_T_O, }, { INST_T_NONE } },
{ "number?",	prim_numberp,	0, 1, 1, { INST_T_s, }, { INST_T_n, } },
{ "odrop",	prim_odrop,	0, 1, 1, { INST_T_O, }, { INST_T_s, } },
{ "ofail",	prim_ofail,	0, 1, 1, { INST_T_O, }, { INST_T_s, } },
{ "ok?",	prim_okp,	0, 1, 1, { INST_T_ANY, }, { INST_T_n, } },
{ "online",	prim_online,	0, 0, 1, { INST_T_NONE }, { INST_T_LIST, INST_T_O, } },
{ "or",	prim_or,	0, 2, 1, { INST_T_ANY, INST_T_ANY, }, { INST_T_n, } },
{ "osucc",	prim_osucc,	0, 1, 1, { INST_T_O, }, { INST_T_s, } },
{ "over",	prim_over,	0, 2, 3, { INST_T_ANY, INST_T_ANY, }, { INST_T_ANY, INST_T_ANY, INST_T_ANY, } },
{ "owner",	prim_owner,	0, 1, 1, { INST_T_O, }, { INST_T_O, } },
{ "pennies",	prim_pennies,	0, 1, 1, { INST_T_O, }, { INST_T_n, } },
{ "pick",	prim_pick,	0, 1, 1, { INST_T_N, }, { INST_T_ANY, } },
{ "player?",	prim_playerp,	0, 1, 1, { INST_T_O, }, { INST_T_n, } },
{ "pop",	prim_pop,	0, 1, 0, { INST_T_ANY, }, { INST_T_NONE } },
{ "prog",	NULL,	0, 0, 0, { INST_T_NONE }, { INST_T_NONE } },
{ "program?",	prim_progp,	0, 1, 1, { INST_T_O, }, { INST_T_n, } },
{ "pronoun_sub",	prim_pronoun,	0, 2, 1, { INST_T_s, INST_T_O, }, { INST_T_s, } },
{ "put",	prim_put,	0, 2, 0, { INST_T_N, INST_T_ANY, }, { INST_T_NONE } },
{ "random",	prim_random,	0, 0, 1, { INST_T_NONE }, { INST_T_n, } },
{ "read",	prim_read,	0, 0, 1, { INST_T_NONE }, { INST_T_S, } },
{ "remove_prop",	prim_rmvprop,	0, 2, 0, { INST_T_S, INST_T_O, }, { INST_T_NONE } },
{ "rinstr",	prim_rinstr,	0, 2, 1, { INST_T_S, INST_T_s, }, { INST_T_n, } },
{ "rmatch",	prim_rmatch,	0, 2, 1, { INST_T_s, INST_T_O, }, { INST_T_o, } },
{ "room?",	prim_roomp,	0, 1, 1, { INST_T_O, }, { INST_T_n, } },
{ "rot",	prim_rot,	0, 3, 3, { INST_T_ANY, INST_T_ANY, INST_T_ANY, }, { INST_T_ANY, INST_T_ANY, INST_T_ANY, } },
{ "rotate",	prim_rotate,	0, 1, 0, { INST_T_n, }, { INST_T_NONE } },
{ "self",	NULL,	0, 0, 0, { INST_T_NONE }, { INST_T_NONE } },
{ "set",	prim_set,	0, 2, 0, { INST_T_S, INST_T_P, }, { INST_T_NONE } },
{ "setdesc",	prim_setdesc,	0, 2, 0, { INST_T_s, INST_T_P, }, { INST_T_NONE } },
{ "setdrop",	prim_setdrop,	0, 2, 0, { INST_T_s, INST_T_P, }, { INST_T_NONE } },
{ "setfail",	prim_setfail,	0, 2, 0, { INST_T_s, INST_T_P, }, { INST_T_NONE } },
{ "setname",	prim_setname,	0, 2, 0, { INST_T_s, INST_T_P, }, { INST_T_NONE } },
{ "setodrop",	prim_setodrop,	0, 2, 0, { INST_T_s, INST_T_P, }, { INST_T_NONE } },
{ "setofail",	prim_setofail,	0, 2, 0, { INST_T_s, INST_T_P, }, { INST_T_NONE } },
{ "setosucc",	prim_setosucc,	0, 2, 0, { INST_T_s, INST_T_P, }, { INST_T_NONE } },
{ "setprop",	prim_setprop,	0, 3, 0, { INST_T_ANY, INST_T_S, INST_T_O, }, { INST_T_NONE } },
{ "setsucc",	prim_setsucc,	0, 2, 0, { INST_T_s, INST_T_P, }, { INST_T_NONE } },
{ "strcat",	prim_strcat,	0, 2, 1, { INST_T_s, INST_T_s, }, { INST_T_s, } },
{ "strcmp",	prim_strcmp,	0, 2, 1, { INST_T_s, INST_T_s, }, { INST_T_n, } },
{ "strcut",	prim_strcut,	0, 2, 2, { INST_T_n, INST_T_s, }, { INST_T_s, INST_T_s, } },
{ "strftime",	prim_strftime,	0, 2, 1, { INST_T_s, INST_T_n, }, { INST_T_s, } },
{ "stringcmp",	prim_stringcmp,	0, 2, 1, { INST_T_s, INST_T_s, }, { INST_T_n, } },
{ "stringncmp",	prim_stringncmp,	0, 3, 1, { INST_T_N, INST_T_s, INST_T_s, }, { INST_T_n, } },
{ "strlen",	prim_strlen,	0, 1, 1, { INST_T_s, }, { INST_T_n, } },
{ "strncmp",	prim_strncmp,	0, 3, 1, { INST_T_N, INST_T_s, INST_T_s, }, { INST_T_n, } },
{ "subst",	prim_subst,	0, 3, 1, { INST_T_S, INST_T_s, INST_T_s, }, { INST_T_s, } },
{ "succ",	prim_succ,	0, 1, 1, { INST_T_O, }, { INST_T_s, } },
{ "swap",	prim_swap,	0, 2, 2, { INST_T_ANY, INST_T_ANY, }, { INST_T_ANY, INST_T_ANY, } },
{ "systime",	prim_systime,	0, 0, 1, { INST_T_NONE }, { INST_T_n, } },
{ "then",	NULL,	0, 0, 0, { INST_T_NONE }, { INST_T_NONE } },
{ "thing?",	prim_thingp,	0, 1, 1, { INST_T_O, }, { INST_T_n, } },
{ "time",	prim_time,	0, 0, 3, { INST_T_NONE }, { INST_T_n, INST_T_n, INST_T_n, } },
{ "var",	NULL,	0, 0, 0, { INST_T_NONE }, { INST_T_NONE } },
{ "variable",	prim_variable,	0, 1, 1, { INST_T_n, }, { INST_T_v, } },
