#define PRIM_bang		0
#define PRIM_mod		1
#define PRIM_mul		2
#define PRIM_add		3
#define PRIM_sub		4
#define PRIM_div		5
#define PRIM_word_begin		6
#define PRIM_word_end		7
#define PRIM_lessthan		8
#define PRIM_lesseq		9
#define PRIM_equal		10
#define PRIM_gtrthan		11
#define PRIM_gtreq		12
#define PRIM_at		13
#define PRIM_getpropv_i		14
#define PRIM_getprops_i		15
#define PRIM_getpropd_i		16
#define PRIM_rmvprop_i		17
#define PRIM_addprop_i		18
#define PRIM_setprop_i		19
#define PRIM_flagp_i		20
#define PRIM_addpennies		21
#define PRIM_addprop		22
#define PRIM_and		23
#define PRIM_atoi		24
#define PRIM_awakep		25
#define PRIM_call		26
#define PRIM_check_moveto		27
#define PRIM_conboot		28
#define PRIM_concount		29
#define PRIM_condbref		30
#define PRIM_conhost		31
#define PRIM_conidle		32
#define PRIM_connections		33
#define PRIM_contents		34
#define PRIM_contime		35
#define PRIM_copyobj		36
#define PRIM_dbcmp		37
#define PRIM_dbref		38
#define PRIM_dbtop		39
#define PRIM_depth		40
#define PRIM_desc		41
#define PRIM_drop		42
#define PRIM_dup		43
#define PRIM_else		44
#define PRIM_execute		45
#define PRIM_exit		46
#define PRIM_exitp		47
#define PRIM_exits		48
#define PRIM_explode		49
#define PRIM_fail		50
#define PRIM_flagp		51
#define PRIM_getlink		52
#define PRIM_getpropd		53
#define PRIM_getprops		54
#define PRIM_getpropv		55
#define PRIM_if		56
#define PRIM_instr		57
#define PRIM_int		58
#define PRIM_intostr		59
#define PRIM_loc		60
#define PRIM_match		61
#define PRIM_moveto		62
#define PRIM_name		63
#define PRIM_next		64
#define PRIM_not		65
#define PRIM_notify		66
#define PRIM_notify_except		67
#define PRIM_numberp		68
#define PRIM_odrop		69
#define PRIM_ofail		70
#define PRIM_okp		71
#define PRIM_online		72
#define PRIM_or		73
#define PRIM_osucc		74
#define PRIM_over		75
#define PRIM_owner		76
#define PRIM_pennies		77
#define PRIM_pick		78
#define PRIM_playerp		79
#define PRIM_pop		80
#define PRIM_prog		81
#define PRIM_progp		82
#define PRIM_pronoun		83
#define PRIM_put		84
#define PRIM_random		85
#define PRIM_read		86
#define PRIM_rmvprop		87
#define PRIM_rinstr		88
#define PRIM_rmatch		89
#define PRIM_roomp		90
#define PRIM_rot		91
#define PRIM_rotate		92
#define PRIM_self		93
#define PRIM_set		94
#define PRIM_setdesc		95
#define PRIM_setdrop		96
#define PRIM_setfail		97
#define PRIM_setname		98
#define PRIM_setodrop		99
#define PRIM_setofail		100
#define PRIM_setosucc		101
#define PRIM_setprop		102
#define PRIM_setsucc		103
#define PRIM_strcat		104
#define PRIM_strcmp		105
#define PRIM_strcut		106
#define PRIM_strftime		107
#define PRIM_stringcmp		108
#define PRIM_stringncmp		109
#define PRIM_strlen		110
#define PRIM_strncmp		111
#define PRIM_subst		112
#define PRIM_succ		113
#define PRIM_swap		114
#define PRIM_systime		115
#define PRIM_then		116
#define PRIM_thingp		117
#define PRIM_time		118
#define PRIM_var_decl		119
#define PRIM_variable		120
#define PRIM_NONE		-1
#define PRIM_PUSH		-2
